### ISSUE TITLE
問題

### ISSUE THREAD

**Issue by Saillxl** [qcf-568/MIML#2]
作者您好，我想請問您有沒有在mmsegmentation庫中使用過這個數據集，爲什麽我就是換了數據集，代碼就運行不了？感謝！

**Comment by qcf-568** [comment]
您好，是在mmsegmentation中使用的，代码怎样报错？

**Comment by qcf-568** [comment]
你好，首先看起来是你的config或mmseg有问题。另外对于MIML数据集，不能用0/1的mask，而应该用原始0-255的mask。

**Comment by qcf-568** [comment]
你可以使用教育邮箱将你的mmseg以及config打包发送到我的邮箱[202221012612@mail.scut.edu.cn](mailto:202221012612@mail.scut.edu.cn) ，之后我可以整理提供一个无bug的版本。

**Comment by Saillxl** [comment]
感谢作者！请问您说的mmseg是指什么

**Comment by qcf-568** [comment]
mmseg是指mmsegmentation这个的文件夹，使用的mmsegmentation都是基于官方库进行二次开发得到的，而非官方原版。

**Comment by fangfangbuaibiancheng** [comment]
在运行代码中遇到了一个小问题，提示我无法加载一个pickle文件，FileNotFoundError :[Errno 2] No such  file or directory：'./new_ rcd.pk'.。想在这里咨询您一下这个pickle文件是一开始要加载的还是运行代码它自己生成的。谢谢～
