### ISSUE TITLE
ModuleNotFoundError: No module named 'mmseg.models.decode_heads.psp_head'

### ISSUE THREAD

**Issue by ciliuciliudebaozi** [qcf-568/MIML#4]
我在推理SPG图片的mask时遇到了这个问题
![image](https://github.com/user-attachments/assets/813e8cf5-ebea-43d1-a78f-df4bf17b1b2b)

**Comment by qcf-568** [comment]
Thank you for your feedback! I have uploaded this [file](https://github.com/qcf-568/MIML/blob/main/models%20for%20CIML/mmseg/models/decode_heads/psp_head.py).
